version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - my-network

  # prometheus:
  #   container_name: prometheus 
  #   image: prom/prometheus:latest
  #   restart: always
  #   volumes:
  #     - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - my-network
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
     - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" #Prometheus metrics exposed by collector
      - "8889:8889" #Prometheus exporter metrics
      - "4317:4317" #OTLP gRPC receiver
    networks:
      - my-network

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:latest
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - my-network

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      - my-network

  service:
    container_name: service
    build:
      context: ./serviceA
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
      # - prometheus
      - otel-collector
      - zipkin
    networks:
      - my-network

  service2:
    container_name: service2
    build:
      context: ./serviceB
    ports:
      - "8181:8181"
    depends_on:
      - jaeger
      # - prometheus
      - otel-collector
      - zipkin
    networks:
      - my-network

networks:
  my-network:
    driver: bridge